spring.application.name=SGR GenAI Application
server.port=8082
spring.profiles.active=@activatedProperties@

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.sahajgyan.in/realms/staging-sahajgyan
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


server.servlet.context-path=/backend-genai

app.logging.transaction.enabled=false
app.logging.transaction.base-dir=/opt/logs/geni
 
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.security.oauth2=ERROR
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=ERROR

ANTHROPIC_API_KEY=
AZURE_OPENAI_ENDPOINT=
AZURE_OPENAI_KEY=

langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true

langchain4j.open-ai.streaming-chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.streaming-chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.streaming-chat-model.log-requests=true
langchain4j.open-ai.streaming-chat-model.log-responses=true

langchain4j.open-ai.api-key=${OPENAI_API_KEY}
langchain4j.google-ai.api-key=${GEMINI_API_KEY}
langchain4j.antropic-ai.api-key=${ANTHROPIC_API_KEY}

langchain4j.azure-open-ai.endpoint: "${AZURE_OPENAI_ENDPOINT}"
langchain4j.azure-open-ai.api-key: "${AZURE_OPENAI_KEY}"
#langchain4j.azure-open-ai.deployment-name: "${AZURE_OPENAI_DEPLOYMENT_NAME}"

# Example: 5 requests per second per user
app.rate-limit.permits-per-minute: 10.0
